//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conductor_()
        {
            this.Venta_ = new HashSet<Venta_>();
        }
    
        public int id { get; set; }
        public string ruc { get; set; }
        public string placaAuto { get; set; }
        public string nombre { get; set; }
        public string Direccion { get; set; }
        public string cuentaBancaria { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public bool activo { get; set; }
        public int idAuto { get; set; }
    
        public virtual TipoAuto_ TipoAuto_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_> Venta_ { get; set; }
    }
}
