//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta_
    {
        public string idCaja { get; set; }
        public int idDoc { get; set; }
        public int idCorrelativo { get; set; }
        public int id { get; set; }
        public Nullable<int> idTarifa { get; set; }
        public bool esParticular { get; set; }
        public string detalle { get; set; }
        public double montoAsignado { get; set; }
        public double IGV { get; set; }
    
        public virtual Tarifa_local Tarifa_local { get; set; }
    }
}
