//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_
    {
        public string idOrdenador { get; set; }
        public int tipoDocumento { get; set; }
        public int correlativo { get; set; }
    
        public virtual Ordenador_ Ordenador_ { get; set; }
    }
}
