//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMV_LOCAL3Entities : DbContext
    {
        public CMV_LOCAL3Entities()
            : base("name=CMV_LOCAL3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Cliente_> Cliente_ { get; set; }
        public virtual DbSet<Conductor_> Conductor_ { get; set; }
        public virtual DbSet<DetalleVenta_> DetalleVenta_ { get; set; }
        public virtual DbSet<Distrito_> Distrito_ { get; set; }
        public virtual DbSet<Documento_> Documento_ { get; set; }
        public virtual DbSet<Moneda_> Moneda_ { get; set; }
        public virtual DbSet<Ordenador_> Ordenador_ { get; set; }
        public virtual DbSet<Retiro_> Retiro_ { get; set; }
        public virtual DbSet<SaldosIniciales_> SaldosIniciales_ { get; set; }
        public virtual DbSet<Sincronizacion_> Sincronizacion_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarifa_local> Tarifa_local { get; set; }
        public virtual DbSet<TipoAuto_> TipoAuto_ { get; set; }
        public virtual DbSet<Turno_> Turno_ { get; set; }
        public virtual DbSet<Usuario_> Usuario_ { get; set; }
        public virtual DbSet<Venta_> Venta_ { get; set; }
        public virtual DbSet<Zona_> Zona_ { get; set; }
    }
}
