//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldosIniciales_
    {
        public int id { get; set; }
        public double saldoInicial { get; set; }
        public double saldoFinal { get; set; }
        public int idMoneda { get; set; }
        public int idTurno { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
    
        public virtual Moneda_ Moneda_ { get; set; }
    }
}
