//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDePuntoDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno_()
        {
            this.Retiro_ = new HashSet<Retiro_>();
        }
    
        public int id { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fin { get; set; }
        public bool estaAbierto { get; set; }
        public Nullable<bool> actualizarCierre { get; set; }
        public string idUsuario { get; set; }
        public string idOrdenador { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
    
        public virtual Ordenador_ Ordenador_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retiro_> Retiro_ { get; set; }
        public virtual Usuario_ Usuario_ { get; set; }
    }
}
